# Generated by Django 4.2.1 on 2024-04-06 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название элемента меню', max_length=100)),
                ('url', models.CharField(help_text='URL элемента меню', max_length=100)),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский элемент меню (пусто для корневых элементов)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.menuitem')),
            ],
        ),
    ]
